# Generated by Django 4.1.5 on 2023-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
