# Generated by Django 4.1.5 on 2023-02-20 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_alter_post_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reply",
        ),
        migrations.AddField(
            model_name="post",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="saved_users",
            field=models.ManyToManyField(
                blank=True, related_name="saved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
