# Generated by Django 4.1.5 on 2023-02-23 10:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=4000, null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="saved_discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Create a discussion",
                "verbose_name_plural": "Create discussions",
            },
        ),
    ]
