site_name: practice_django

site_dir: 'wiki/GENERIC/generic/build'

nav:
    - index: index.md
    - Dev: dev.md
    - pip: pip.md
    - settings: settings.md
    - Blog: blog/models.md
    - Dev blog: blog\dev_blog.md

theme:
    name: material

dev_addr:
    127.0.0.1:8200

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - toc:
        permalink: True

plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true

site_author:
    Roman
